### PR TITLE
Add integration test 

### PR DESCRIPTION
**Pull request by Janekdererste**
which parses andorra, since it is sufficiently small.

### CODE REVIEW

**Comment by mrieser** [comment]
This integration test fails the Weekly Build: http://ci.matsim.org:8080/job/Weekly%20Builds/86

```
Running org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReaderIT
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.856 sec <<< FAILURE! - in org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReaderIT
test_andorra(org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReaderIT)  Time elapsed: 2.591 sec  <<< FAILURE!
java.lang.AssertionError
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReaderIT.test_andorra(SupersonicOsmNetworkReaderIT.java:32)
```

Most likely it does not correctly handle white-space in the path name, as the Weekly Build is the only job on the CI server that has a white space in its directory name, and the test passes in all other jobs. Can you have a look at it and try to fix it?

**Comment by Janekdererste** [comment]
I had a look into the reports of the weekly build but I can't find the output of the failing test.

http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/osm/target/surefire-reports/

@mrieser am I looking in the wrong place?

**Comment by mrieser** [comment]
It's an integration test, which gets run by the failsafe-plugin and not the surefire-plugin:
http://ci.matsim.org:8080/job/Weekly%20Builds/ws/matsim/contribs/osm/target/failsafe-reports/

**Comment by Janekdererste** [comment]
Hm, I looked into the output and everything looks as expected. The file which is supposed to be parsed is loaded and the comparison network is loaded. Then in the end the assertion fails (not expected). 

I tried to run the test on my machine inside a folder with spaces. Both the loading of the files and the assertion work as expected. 

How should I proceed from here? Especially, since the test is also passing on the travis set up?

**Comment by Janekdererste** [comment]
trying to get a better understanding with https://github.com/matsim-org/matsim/pull/768

**Pull request merged**
