### PR TITLE
double-checked since the beginning of time :)

### PR DESCRIPTION
**Pull request by neuma**

### CODE REVIEW

**Comment by neuma** [comment]
@jfbischoff This is getting more and more annoying. This time the AppVeyors passed but Travis did not succeed. The error trace seems somewhat random to me. Maybe you see more...

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project hybridsim: Compilation failure
[ERROR] error: error reading /home/travis/.m2/repository/io/netty/netty-codec-http2/4.1.0.CR3/netty-codec-http2-4.1.0.CR3.jar; error in opening zip file

caused by

> [ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /home/travis/.m2/repository/io/netty/netty-codec-http2/4.1.0.CR3/netty-codec-http2-4.1.0.CR3.jar; error in opening zip file
[INFO] 1 error

image

**Comment by jfbischoff** [comment]
No, I also don't see more. But I agree on the annoyance :-(

**Comment by jfbischoff** [comment]
okay, @neuma , I'm now giving up on this one. No idea what's the matter here.

**Comment by jfbischoff** [comment]
Wonders do happen.

**Comment by michalmac** [comment]
On the travis build webpage: "more options"->"caches" (upper right corner).

And then instead of restarting the whole build, you can click on each pending job to restart it (could be like 40 clicks with this (too) huge project).

**Pull request merged**
