### PR TITLE
Drt mode setup bugfix

### PR DESCRIPTION
**Pull request by vsp-gleich**
Let drt really use the mode set in DrtConfigGroup, set DrtStageActivityType accordingly

### CODE REVIEW

**Comment by michalmac** [comment]
Thanks, @vsp-gleich !
The only thing I am not sure about is whether we really want to have `drtStageActivityType` inside `Config`. For me, `Config` is something that directly comes from the input file. It is a bit like adding `Scenario` to `Config`. Is there anything stopping us from injecting `DrtStageActivityType` via guice??

**Comment by jfbischoff** [comment]
Good thought, @michalmac . 
> Is there anything stopping us from injecting DrtStageActivityType via guice??
The complicated thing is, that we need the Stage Activity names before the controler is created (namely, in DrtControlerGenerator, where we adapt the config). 

What's your intuition on this?

**Comment by michalmac** [comment]
`DrtStageActivityType` is cheap to build so it is now created locally when needed. Since we have distinct local instances, I added `hashCode()` and `equals()` (see guidelines for `StageActivityTypes`).

Still one issue is unsolved -- see the commented out line: dc347c2

**Comment by jfbischoff** [comment]
Walk Router is used in DRT Routing module, so there is no need to add routing parameters for DRT_walk to the config. Sorry about the confusion @vsp-gleich

**Comment by vsp-gleich** [comment]
Thank you @michalmac and @jfbischoff !

**Pull request merged**
