### PR TITLE
network filter manager did not recreate link attributes

### PR DESCRIPTION
**Pull request by dts-ait**
add this and also write a unit test
clearer logging of filtering result

### CODE REVIEW

**Comment by dts-ait** [comment]
I accidentally also committed "fix crash in energy calculation", this should not be merged here as its solution is discussed in https://matsim.atlassian.net/browse/MATSIM-924

**Comment by dts-ait** [comment]
it would be great if somebody could merge this (or give feedback) - thanks!

**Comment by kainagel** [comment]
The "automerge" label should have merged it automatically.  Looks more like there is some problem with jenkins, or the jenkins <-> github integration.

**Comment by jfbischoff** [comment]
Maybe the automerge tag does not work if the PR author does not have merge rights?

**Comment by michalmac** [comment]
I do not think this PR should be merged before the cleaning it up (it contains 1 fix commit, 1 commit that should not be merged and then a series of merge commits).

**Comment by michalmac** [comment]
I created a PR from this one: #528 . Please (auto)merge it if it looks okay to you. Thanks!

**Pull request closed without merging**
